#!/bin/bash
IFS=$'\n\t'
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

function build() {
  clean
  echo -n "Building src .. "
  tsc --outDir "out"
  echo "ok"
  cd src
  for d in $(find . -mindepth 1 -maxdepth 1 -type d | sort -n); do
    echo -n "Copying files for $d .. "
    cd "$d"
    basename=$(basename "$(pwd)")
    find . -mindepth 1 -maxdepth 1 -type f -not -name '*.ts' -exec cp {} "../../out/${basename}" \;
    perl -0777 -ne "print \$1 if /input = [\`']([^\`']+)/" index.test.ts >"../../out/${basename}/sample.txt"
    echo "ok"
    cd ..
  done
  cd ..
  cp index.html out/
}

function clean() {
  if [[ -d "out" ]]; then
    find "out" -xdev -type f -delete
    find "out" -xdev -type d -delete
  fi
}

function solve() {
  local name="0$1"
  name=${name: -2}
  node -r ts-node/register/transpile-only "src/$name"
}

case "${1:-build}" in
  build ) build ;;
  clean ) clean ;;
  solve ) shift; solve "$@" ;;
  * ) echo "ERROR" >&2 && exit 1
esac